spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-language
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate-ddl: false
        ddl-auto: false
    hibernate:
        ddl-auto: validate
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

liquibase:
  enabled: true
